---
- name: Verify /etc/docker directory exists
  become_method: sudo
  become: true
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create /etc/docker/daemon.json
  become: true
  become_method: sudo
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644

- name: Remove old versions of Docker
  become: true
  become_method: sudo
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    update_cache: yes
    purge: yes

- name: Verify Docker GPG key is present
  become: true
  become_method: sudo
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Verify Docker repository is present
  become: true
  become_method: sudo
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Install Docker
  become: true
  become_method: sudo
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Add "{{ansible_user}}" user to "docker" group
  become: true
  become_method: sudo
  user:
    name: "{{ansible_user}}"
    state: present
    groups: docker

- name: Reset ssh session after group change
  meta: reset_connection
