---
- name: Gather pip package facts
  pip_package_info:
    clients: ['pip3']
  register: pip_stats

- name: Install Python library "docker"
  when: "'docker' not in pip_stats.packages.pip3"
  pip:
    executable: pip3
    name: docker

- name: Install Python library "jsondiff"
  when: "'jsondiff' not in pip_stats.packages.pip3"
  pip:
    executable: pip3
    name: jsondiff

- name: Install Python library "PyYAML"
  when: "'PyYAML' not in pip_stats.packages.pip3"
  pip:
    executable: pip3
    name: PyYAML

- name: Verify Docker dependencies
  become: true
  become_method: sudo
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    force_apt_get: true
    update_cache: yes

- name: Install docker-compose
  become: true
  become_method: sudo
  shell: curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
