---
- include_tasks: registry-namespace.yml

- name: Check if secret exists
  shell: kubectl -n {{registry_namespace}} get secret {{registry_fqdn}}.tls-secret
  no_log: true
  ignore_errors: true
  register: secret_status

- name: Update host facts for secret status
  set_fact:
    secret_missing: "{{secret_status.rc != 0}}"

- include_tasks: registry-generate-ssl.yml
  when: secret_missing and registry_ssl_generate and registry_fqdn
  vars:
    ssl_filename: "{{registry_fqdn}}"
    ssl_cn_name: "{{registry_fqdn}}"
    ssl_subj_opt: "/C=US/ST=SELF/L=SIGNED/O=SELF_SIGNED/OU=SELF_SIGNED"

- include_tasks: registry-custom-ssl.yml
  when: secret_missing
  vars:
    ssl_key_path: "{{registry_ssl_key_path}}"
    ssl_crt_path: "{{registry_ssl_cert_path}}"
    secret_name: "{{registry_fqdn}}.tls-secret"
    secret_namespace: "{{registry_namespace}}"

- include_tasks: registry-save-ssl.yml
  when: registry_ssl_local_save is defined
  vars:
    secret_name: "{{registry_fqdn}}.tls-secret"
    secret_namespace: "{{registry_namespace}}"
    ssl_save_dir: "{{registry_ssl_local_save}}"

- include_tasks: registry-labels.yml
  vars:
    registrynode: "{{registry_services_name}}"

- include_tasks: registry-service.yml

- name: Save fact with internalUri for registry service
  set_fact:
    registry_internalUri: "{{registry_services_name}}.{{registry_namespace}}:{{registry_port}}"
    cacheable: yes

- debug:
    msg: "Registry is available internal to cluster at '{{registry_internalUri}}' (non tls)"
