---
- name: Remove any existing remote temp files in /tmp/registry_tls
  become_method: sudo
  become: true
  file:
    path: /tmp/registry_tls
    state: absent

- name: Verify remote temp directory /tmp/registry_tls exists
  become: true
  become_method: sudo
  file:
    path: /tmp/registry_tls
    state: directory
    mode: 0777

- name: Export tls cert from {{secret_name}}
  shell: |
    kubectl -n {{secret_namespace}} get secret {{secret_name}} -o json \
      | jq -r '.data["tls.crt"]' \
      | base64 --decode \
      > /tmp/registry_tls/{{secret_name}}.crt

- name: Export tls key from {{secret_name}}
  shell: |
    kubectl -n {{secret_namespace}} get secret {{secret_name}} -o json \
      | jq -r '.data["tls.key"]' \
      | base64 --decode \
      > /tmp/registry_tls/{{secret_name}}.key

- name: Verify save dir directory {{ssl_save_dir}} exists
  local_action:
    module: file
    path: "{{ssl_save_dir}}"
    state: directory
    mode: 0755

- name: Fetch /tmp/registry_tls/{{secret_name}}.crt to {{ssl_save_dir}}
  become_method: sudo
  become: true
  fetch:
    src: "/tmp/registry_tls/{{secret_name}}.crt"
    dest: "{{ssl_save_dir}}/"

- name: Fetch /tmp/registry_tls/{{secret_name}}.key to {{ssl_save_dir}}
  become_method: sudo
  become: true
  fetch:
    src: "/tmp/registry_tls/{{secret_name}}.key"
    dest: "{{ssl_save_dir}}/"

- name: Cleanup local temp files in /tmp/registry_tls
  run_once: true
  become_method: sudo
  become: true
  local_action:
    module: file
    path: /tmp/registry_tls
    state: absent
