---
- name: Remove any existing remote temp files in /tmp/registry_tls
  become_method: sudo
  become: true
  file:
    path: /tmp/registry_tls
    state: absent

- name: Remove any existing local temp files in /tmp/registry_tls
  become_method: sudo
  become: true
  local_action:
    module: file
    path: /tmp/registry_tls
    state: absent

- name: Verify remote temp directory /tmp/registry_tls exists
  become: true
  become_method: sudo
  file:
    path: /tmp/registry_tls
    state: directory
    mode: 0755

- name: Create SSL Certificate for {{ssl_cn_name}}
  become: true
  become_method: sudo
  shell: |
    cd /tmp/registry_tls
    openssl req -x509 -nodes \
      -days {{ssl_expire_days}} \
      -newkey rsa:{{ssl_key_size}} \
      -keyout {{ssl_filename}}.key \
      -out {{ssl_filename}}.crt \
      -subj "/CN={{ssl_cn_name}}{{ssl_subj_opt}}"

- name: Fetch generated files
  become_method: sudo
  become: true
  fetch:
    src: /tmp/registry_tls/{{item}}
    dest: /tmp/registry_tls
  with_items:
    - "{{ssl_filename}}.key"
    - "{{ssl_filename}}.crt"

- name: Update host facts ssl certs
  set_fact:
    cacheable: yes
    registry_ssl_cert_path: /tmp/registry_tls/{{inventory_hostname}}/tmp/registry_tls/{{registry_fqdn}}.crt
    registry_ssl_key_path: /tmp/registry_tls/{{inventory_hostname}}/tmp/registry_tls/{{registry_fqdn}}.key

- name: Cleanup remote temp files in /tmp/registry_tls
  become_method: sudo
  become: true
  file:
    path: /tmp/registry_tls
    state: absent
