---
- name: Remove any existing remote temp files in /tmp/registry_tls
  become_method: sudo
  become: true
  file:
    path: /tmp/registry_tls
    state: absent

- name: Verify remote temp directory /tmp/registry_tls exists
  become: true
  become_method: sudo
  file:
    path: /tmp/registry_tls
    state: directory
    mode: 0755

- name: Copy SSL Cert file to remote Host
  become_method: sudo
  become: true
  copy:
    src: "{{ssl_crt_path}}"
    dest: /tmp/registry_tls/tls.crt

- name: Copy SSL Key file to remote Host
  become_method: sudo
  become: true
  copy:
    src: "{{ssl_key_path}}"
    dest: /tmp/registry_tls/tls.key

- name: Create k8s Secret {{secret_name}}
  shell: |
    cd /tmp/registry_tls
    kubectl -n {{secret_namespace}} create secret tls {{secret_name}} \
      --key tls.key \
      --cert tls.crt

- name: Cleanup remote temp files in /tmp/registry_tls
  become_method: sudo
  become: true
  file:
    path: /tmp/registry_tls
    state: absent

- name: Cleanup local temp files in /tmp/registry_tls
  run_once: true
  become_method: sudo
  become: true
  local_action:
    module: file
    path: /tmp/registry_tls
    state: absent
