---
- name: Remove any existing remote temp files in /tmp/k8s_tls
  become_method: sudo
  become: true
  file:
    path: /tmp/k8s_tls
    state: absent

- name: Remove any existing local temp files in /tmp/k8s_tls
  become_method: sudo
  become: true
  local_action:
    module: file
    path: /tmp/k8s_tls
    state: absent

- name: Verify remote temp directory /tmp/k8s_tls exists
  become: true
  become_method: sudo
  file:
    path: /tmp/k8s_tls
    state: directory
    mode: 0755

- name: Create SSL Certificate for {{ssl_cn_name}}
  become: true
  become_method: sudo
  shell: |
    cd /tmp/k8s_tls
    openssl req -x509 -nodes \
      -days {{ssl_expire_days}} \
      -newkey rsa:{{ssl_key_size}} \
      -keyout tls.key \
      -out tls.crt \
      -subj "/CN={{ssl_cn_name}}{{ssl_subj_opt}}"
    chmod 755 tls.*

- name: Create k8s Secret {{secret_name}} in {{secret_namespace}}
  shell: |
    cd /tmp/k8s_tls
    kubectl -n {{secret_namespace}} create secret tls {{secret_name}} \
      --key tls.key \
      --cert tls.crt

- name: Cleanup remote temp files in /tmp/k8s_tls
  become_method: sudo
  become: true
  file:
    path: /tmp/k8s_tls
    state: absent
