---
- name: Remove any existing local temp files in /tmp/k8s/
  run_once: true
  become_method: sudo
  become: true
  local_action:
    module: file
    path: /tmp/k8s_etcd
    state: absent

- name: Create/refresh cluster discovery config file
  shell: |
    kubectl get configmap cluster-info \
      --namespace kube-public \
      --output=jsonpath='{.data.kubeconfig}' \
      > discovery.yaml

- name: Apply cluster discovery config file
  become_method: sudo
  become: true
  shell: |
    mv discovery.yaml /etc/kubernetes/discovery.yaml
    chown root:root /etc/kubernetes/discovery.yaml

- name: Fetch /etc/kubernetes/discovery.yaml from host
  become_method: sudo
  become: true
  fetch:
    src: /etc/kubernetes/discovery.yaml
    dest: /tmp/k8s/
