---
- include_tasks: controller.yml
  when: inventory_hostname == k8s_manager_nodes[0] and ('k8s_enabled' not in ansible_facts or not k8s_enabled)

- include_tasks: networking-calico.yml
  when: inventory_hostname == k8s_manager_nodes[0]

- include_tasks: networking-policy.yml
  when: inventory_hostname == k8s_manager_nodes[0] and enable_default_networking_policy

- include_tasks: metrics-service.yml
  when: inventory_hostname == k8s_manager_nodes[0]
  vars:
    metrics_server_version: v0.3.7

- include_tasks: get-discovery-yaml.yml
  when: inventory_hostname == k8s_manager_nodes[0]

- include_tasks: update-discovery-yaml.yml
  when: inventory_hostname != k8s_manager_nodes[0]

- include_tasks: manager.yml
  when: inventory_hostname in k8s_manager_nodes and inventory_hostname != k8s_manager_nodes[0] and ('k8s_enabled' not in ansible_facts or not k8s_enabled)

- include_tasks: worker.yml
  when: inventory_hostname in k8s_worker_nodes and ('k8s_enabled' not in ansible_facts or not k8s_enabled)

- include_tasks: install-calicoctl.yml
  when: inventory_hostname in k8s_manager_nodes

- name: Check if default tls secret exists
  when: inventory_hostname == k8s_manager_nodes[0]
  shell: kubectl -n default get secret tls-secret
  no_log: true
  ignore_errors: true
  register: secret_status

- include_tasks: create-tls-cert.yml
  when: inventory_hostname == k8s_manager_nodes[0] and secret_status.rc != 0
  vars:
    ssl_cn_name: "*.{{network_domain_name}}"
    ssl_subj_opt: "/C=US/ST=SELF/L=SIGNED/O=SELF_SIGNED/OU=SELF_SIGNED"
    secret_name: "tls-secret"
    secret_namespace: default
