---
- name: Copy discovery.yaml to k8s host
  become_method: sudo
  become: true
  copy:
    src: "/tmp/k8s/{{k8s_manager_nodes[0]}}/etc/kubernetes/discovery.yaml"
    dest: /etc/kubernetes/
    mode: 0644
    owner: root
    group: root
