---
- name: Copy discovery.yaml to k8s host
  become_method: sudo
  become: true
  copy:
    src: "{{playbook_dir}}/config/{{k8s_manager_nodes[0]}}/etc/kubernetes/discovery.yaml"
    dest: /etc/kubernetes/discovery.yaml
    mode: 0644
    owner: root
    group: root

- name: "Create /etc/kubernetes/kubeadmcfg.yaml"
  become: true
  become_method: sudo
  template:
    src: kubeadmcfg-worker-yaml.j2
    dest: "/etc/kubernetes/kubeadmcfg.yaml"
    mode: 0644
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"

- name: Fetch generated /etc/kubernetes/kubeadmcfg.yaml
  become_method: sudo
  become: true
  fetch:
    src: /etc/kubernetes/kubeadmcfg.yaml
    dest: "{{playbook_dir}}/config"

- name: Join node to k8s as new Worker
  become_method: sudo
  become: true
  shell: kubeadm join --config /etc/kubernetes/kubeadmcfg.yaml

- name: Update host facts regarding k8s install
  set_fact:
    cacheable: yes
    k8s_enabled: yes
