---
- name: "Create /home/{{ansible_user}}/kubeadmcfg.yaml"
  become: true
  become_method: sudo
  template:
    src: kubeadmcfg-worker-yaml.j2
    dest: "/home/{{ansible_user}}/kubeadmcfg.yaml"
    mode: 0644
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"

- name: Fetch generated /home/{{ansible_user}}/kubeadmcfg.yaml
  become_method: sudo
  become: true
  fetch:
    src: /home/{{ansible_user}}/kubeadmcfg.yaml
    dest: "{{playbook_dir}}/generated"

- name: Join node to k8s as new Worker
  become_method: sudo
  become: true
  shell: |
    kubeadm join --config kubeadmcfg.yaml

- name: Update host facts regarding k8s install
  set_fact:
    cacheable: yes
    k8s_enabled: yes
