---
- name: Create /etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf
  become: true
  become_method: sudo
  template:
    src: 20-etcd-service-manager-conf.j2
    dest: /etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf
    mode: 0640

- name: Restart Sysctl Daemon
  become: true
  become_method: sudo
  shell: systemctl daemon-reload

- name: Restart Kubelet Service
  become: true
  become_method: sudo
  service:
    name: kubelet
    state: restarted
