---
- name: Check if Gluster plugin has already been initialized
  shell: docker plugin inspect glusterfs
  register: gluster_plugin_status
  no_log: true
  ignore_errors: true

- name: Install Docker Gluster plugin
  shell: docker plugin install --alias glusterfs trajano/glusterfs-volume-plugin --grant-all-permissions --disable
  when: gluster_plugin_status.rc != 0

- name: Set Gluster plugin to use Gluster nodes
  shell: docker plugin set glusterfs SERVERS={{gluster_heketi_nodes | list | join(',')}}
  when: gluster_plugin_status.rc != 0

- name: Enable Gluster plugin
  shell: docker plugin enable glusterfs
  when: gluster_plugin_status.rc != 0
