---
- name: Install Python 3
  become: true
  become_method: sudo
  apt:
    pkg:
      - python3
      - python3-pip
      - python3-apt
    state: present
    update_cache: yes

- name: Gather pip package facts
  pip_package_info:
    clients: ['pip3']
  register: pip_stats
