---
- name: Verify config directory /ansible_generated_configs
  become_method: sudo
  become: true
  file:
    path: /ansible_generated_configs
    state: directory

- name: Create /ansible_generated_configs/node-provider-id.yaml
  become: true
  become_method: sudo
  template:
    src: node-provider-id-yaml.j2
    dest: /ansible_generated_configs/node-provider-id.yaml
    mode: 0644

- name: Fetch generated /ansible_generated_configs/node-provider-id.yaml
  become_method: sudo
  become: true
  fetch:
    src: /ansible_generated_configs/node-provider-id.yaml
    dest: "{{playbook_dir}}/config"

- name: Apply providerID to node
  shell: kubectl patch node {{cluster_node_name}} --patch "$(cat /ansible_generated_configs/node-provider-id.yaml)"

- name: Clean up temp files in /ansible_generated_configs
  become_method: sudo
  become: true
  file:
    path: /ansible_generated_configs
    state: absent
