---
- name: Update cached facts for {{network_ip_address}}
  delegate_to: "{{network_ip_address}}"
  delegate_facts: true
  set_fact:
    cacheable: yes
    vm_name: "{{vm_name}}"

- name: Refresh status of deployed Virtual Machines
  when: "all_vms is not defined"
  local_action:
    module: vmware_vm_info
    hostname: "{{vcenter_hostname}}"
    username: "{{vcenter_username}}"
    password: "{{vcenter_password}}"
    validate_certs: false
    vm_type: vm
  register: vm_info

- when: "all_vms is not defined"
  set_fact:
    all_vms: "{{vm_info.virtual_machines | map(attribute='guest_name') | list}}"

- when: "vm_name not in all_vms"
  include_tasks: create-from-template.yml
