---
- include_tasks: create-vm.yml

- import_tasks: configure-vm.yml
  delegate_to: "{{vm_ip_address}}"

# remove stale vapp properties from image
- import_tasks: clean/vapp-prop-clean.yml

# clean image and shutdown (ready for template/clone)
- import_tasks: clean/cloud-init-clean.yml
  delegate_to: "{{vm_ip_address}}"

# wait for host to shut down
- name: Wait for VM to shut down
  wait_for:
    host: "{{vm_ip_address}}"
    port: 22
    state: stopped
    delay: 0
    sleep: 1
    timeout: 300

- name: Wait for VM to finalize
  wait_for:
    timeout: 15

# convert vm to template
- import_tasks: clean/convert-to-template.yml
