---
- include_tasks: create-vm.yml

- import_tasks: configure-vm.yml
  delegate_to: "{{vm_ip_address}}"

# remove stale vapp properties from image
- import_tasks: clean/vapp-prop-clean.yml

# clean image and shutdown (ready for template/clone)
- import_tasks: clean/cloud-init-clean.yml
  delegate_to: "{{vm_ip_address}}"

# convert vm to template
- import_tasks: clean/convert-to-template.yml
