---
- name: Verify config directory /ansible_generated_configs
  become_method: sudo
  become: true
  file:
    path: /ansible_generated_configs
    state: directory

- name: Create /ansible_generated_configs/grafana-service.yaml
  become: true
  become_method: sudo
  template:
    src: grafana-service-yaml.j2
    dest: /ansible_generated_configs/grafana-service.yaml
    mode: 0644

- name: Fetch generated /ansible_generated_configs/grafana-service.yaml
  become_method: sudo
  become: true
  fetch:
    src: /ansible_generated_configs/grafana-service.yaml
    dest: "{{playbook_dir}}/config"

- name: Apply /ansible_generated_configs/grafana-service.yaml
  shell: kubectl apply -f /ansible_generated_configs/grafana-service.yaml

- name: Copy default/tls-secret to {{grafana_namespace}}/{{grafana_tls_secret}}
  ignore_errors: true
  shell: |
    kubectl -n default get secret tls-secret -o json \
      | jq '.metadata.name = "{{grafana_tls_secret}}"' \
      | jq '.metadata.namespace = "{{grafana_namespace}}"' \
      | kubectl create -f -

- name: Clean up temp files in /ansible_generated_configs
  become_method: sudo
  become: true
  file:
    path: /ansible_generated_configs
    state: absent
