---
- name: Gather meta data for snapshot generation
  set_fact:
    cacheable: yes
    vm_name: "{{hostvars[inventory_hostname].ansible_facts.vm_name}}"

- name: Gather meta data for snapshot generation
  set_fact:
    snapshot_prefix: "{{now(utc=True).strftime('%Y%m%dT%H%M%S%f')}}"

- name: Generate snapshot name
  set_fact:
    snapshot_name: "{{snapshot_prefix}}-{{vm_name}}"

- name: Create snapshot for VM
  vars:
    datacenter: "{{vcenter_datacenter if vcenter_datacenter is defined else 'ha-datacenter'}}"
  local_action:
    module: vmware_guest_snapshot
    hostname: "{{vcenter_hostname}}"
    username: "{{vcenter_username}}"
    password: "{{vcenter_password}}"
    validate_certs: false
    datacenter: "{{datacenter}}"
    folder: "/{{datacenter}}/vm/"
    name: "{{vm_name}}"
    state: present
    memory_dump: yes
    snapshot_name: "{{snapshot_name}}"
    description: "Anisible Snapshot {{snapshot_name}}"

- name: Create lastSnapshots fact array if it does not exist
  when: hostvars[inventory_hostname].ansible_facts.lastSnapshots is not defined
  set_fact:
    cacheable: yes
    lastSnapshots: []

- name: Push snapshot_name to lastSnapshots array
  set_fact:
    cacheable: yes
    lastSnapshots: "{{((hostvars[inventory_hostname].ansible_facts.lastSnapshots | list) + ([snapshot_name] | list)) | unique | list}}"
