---
- name: Update IP Tables
  become: true
  become_method: sudo
  shell: |
    cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    EOF
    sudo sysctl --system

- name: Verify k8s GPG key is present
  become: true
  become_method: sudo
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Update k8s Sources
  become: true
  become_method: sudo
  shell: |
    cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
    deb https://apt.kubernetes.io/ kubernetes-xenial main
    EOF

- name: Create /etc/docker/daemon.json
  become: true
  become_method: sudo
  template:
    src: daemon_json.j2
    dest: /etc/docker/daemon.json
    mode: 0775

- name: Restart docker service
  become: true
  become_method: sudo
  service:
    name: docker
    state: restarted

- name: Install kubelet, kubeadm, kubectl
  become: true
  become_method: sudo
  apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Lock installed versions of kubelet, kubeadm, kubectl
  become: true
  become_method: sudo
  shell: apt-mark hold kubelet kubeadm kubectl
